name: dna_simulator
description: A simple program that simulates some aspects of our genetic code.
version: 0.1.0
author: KalilDev <kalilgamer0@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  equatable:

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
